### ISSUE TITLE
colors.use not working with split.by in do_DimPlot

### ISSUE THREAD

**Issue by fatimasnc** [cran/SCpubr#1]
Hi @enblacar,

Thanks so much for developing this package! I'm loving it.
Unfortunately, I just stumbled upon something: When I use `do_Dimplot` with the `split.by` option, I cannot set all the colors for my identities to the same (which I'm trying to do with a vector of the color "black" repeated as many times as `Idents` I have.

Here's my code:
 
```
library (Seurat)
library (tidyverse)
library (reshape2) 
library (sctransform)
library (MetBrewer)
library (viridis)
library (ggthemes) 
library (presto)
library (simspec)
library (SCpubr)
library (janitor)
library (gplots)
library (Matrix)

cols_black_22 <- rep ("black", times = 22)
names (cols_black_22) <- levels (seurat$Idents)
SCpubr::do_DimPlot (seurat, split.by = "Idents",  legend.position = "none", font.size = 24, colors.use = cols_black_22)
```
And the error I get is the following: `Error in colors.use[[iteration]] : subscript out of bounds`

I have checked that the number of elements in my named vector `cols_black_all` is the same as the number of `Idents` in my Seurat object. Also, if I exchange `split.by` for `group.by` I get no errors. Why is it then failing to iterate through the vector of colors? Am I missing something here is this a bug?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by fatimasnc** [comment]
Thanks @gaborcsardi, I have posted now in the right place. I just cannot find the way to delete this one...

**Comment by gaborcsardi** [comment]
You can't delete it, but you can close it.
